# Generated by Django 3.2.8 on 2021-10-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('necktieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='d_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
