# Generated by Django 3.2.8 on 2021-10-28 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('necktieapp', '0004_auto_20211027_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='d_state',
            new_name='d_specialization',
        ),
        migrations.RenameField(
            model_name='doctors',
            old_name='d_surnam',
            new_name='d_surname',
        ),
    ]
